import { COURT } from '../domain/court';
import type { DrillDefinitionV1, ShotDefinitionV1 } from './types';

const ground = (
  id: string,
  label: string,
  cue: string,
  x: number,
  z: number,
  paceKmh: number,
  spin: ShotDefinitionV1['spin'],
  direction: ShotDefinitionV1['direction'],
  depth: ShotDefinitionV1['depth'],
  extras: Partial<ShotDefinitionV1> = {},
): ShotDefinitionV1 => ({
  schemaVersion: 1,
  id,
  label,
  cue,
  family: 'groundstroke',
  source: { x: 0, y: 1.15, z: COURT.halfLength - 0.65 },
  target: { x, z },
  paceKmh,
  spin,
  surface: 'hard',
  opponentHand: 'right',
  direction,
  depth,
  ...extras,
});

const serve = (
  id: string,
  label: string,
  sourceX: number,
  targetX: number,
  targetZ: number,
  paceKmh: number,
  spin: ShotDefinitionV1['spin'],
  direction: ShotDefinitionV1['direction'],
  hand: ShotDefinitionV1['opponentHand'] = 'right',
  rhythm: NonNullable<ShotDefinitionV1['serveRhythm']> = 'normal',
): ShotDefinitionV1 => ({
  schemaVersion: 1,
  id,
  label,
  cue: label.toUpperCase(),
  family: 'serve',
  source: { x: sourceX, y: 2.55, z: COURT.halfLength - 0.18 },
  target: { x: targetX, z: targetZ },
  paceKmh,
  spin,
  surface: 'hard',
  opponentHand: hand,
  serveRhythm: rhythm,
  direction,
  depth: 'Service box',
});

export const SHOTS: readonly ShotDefinitionV1[] = [
  ground('fh-cross-deep', 'Forehand crosscourt deep', 'FOREHAND', -2.7, -9.5, 82, 'topspin', 'Near left', 'Deep', {
    cameraMotion: { to: { lateral: -1.25, yaw: 2.5 }, duration: 1.25 },
  }),
  ground('fh-cross-mid', 'Forehand crosscourt medium', 'FOREHAND', -2.4, -7.4, 76, 'topspin', 'Near left', 'Mid'),
  ground('fh-line-deep', 'Forehand down the line', 'FOREHAND', 2.7, -9.35, 86, 'flat', 'Near right', 'Deep'),
  ground('fh-inside-out', 'Inside-out forehand', 'FOREHAND', -3.05, -8.7, 88, 'topspin', 'Near left', 'Deep'),
  ground('bh-cross-deep', 'Backhand crosscourt deep', 'BACKHAND', 2.65, -9.4, 80, 'topspin', 'Near right', 'Deep', {
    backhandStyle: 'two-handed', cameraMotion: { to: { lateral: 1.25, yaw: -2.5 }, duration: 1.25 },
  }),
  ground('bh-cross-high', 'Heavy backhand crosscourt', 'BACKHAND', 2.35, -8.65, 70, 'kick', 'Near right', 'Deep'),
  ground('bh-line-deep', 'Backhand down the line', 'BACKHAND', -2.65, -9.25, 84, 'flat', 'Near left', 'Deep', { backhandStyle: 'one-handed' }),
  ground('body-neutral', 'Neutral ball to body', 'BODY', 0, -8.25, 68, 'topspin', 'Body', 'Deep'),
  ground('short-angle-left', 'Short angle left', 'MOVE LEFT', -3.35, -5.9, 62, 'topspin', 'Near left', 'Short'),
  ground('short-angle-right', 'Short angle right', 'MOVE RIGHT', 3.35, -5.9, 62, 'topspin', 'Near right', 'Short'),
  ground('defensive-high-left', 'High defensive left', 'HIGH LEFT', -2.6, -8.1, 58, 'kick', 'Near left', 'Deep'),
  ground('slice-low-right', 'Low slice right', 'LOW RIGHT', 2.35, -7.7, 64, 'slice', 'Near right', 'Mid'),
  serve('serve-deuce-t', 'Deuce flat T', -2.7, -0.45, -4.45, 154, 'flat', 'Body'),
  serve('serve-deuce-wide', 'Deuce slice wide', -2.7, 3.15, -4.7, 138, 'slice', 'Near right', 'right', 'compact'),
  serve('serve-deuce-body', 'Deuce body', -2.7, 0.8, -4.5, 145, 'flat', 'Body'),
  serve('serve-ad-t', 'Ad flat T', 2.7, 0.45, -4.45, 154, 'flat', 'Body', 'right', 'compact'),
  serve('serve-ad-wide', 'Ad kick wide', 2.7, -3.15, -4.7, 132, 'kick', 'Near left'),
  serve('serve-ad-body', 'Ad body', 2.7, -0.8, -4.5, 143, 'topspin', 'Body', 'right', 'compact'),
  serve('serve-left-deuce-wide', 'Lefty deuce wide', 2.7, 3.1, -4.65, 140, 'slice', 'Near right', 'left', 'normal'),
  serve('serve-left-ad-wide', 'Lefty ad wide', -2.7, -3.1, -4.65, 136, 'kick', 'Near left', 'left', 'compact'),
  ground('approach-feed', 'Approach ball', 'ADVANCE', 1.8, -6.5, 70, 'topspin', 'Near right', 'Short', {
    family: 'approach',
    cameraMotion: { to: { behindBaseline: -4.2, fov: 76 }, duration: 1.5 },
  }),
  ground('half-volley-body', 'Half-volley body feed', 'HALF VOLLEY', 0.2, -3.8, 66, 'slice', 'Body', 'Short', {
    family: 'half-volley', source: { x: 0.4, y: 0.88, z: 3.6 },
    cameraMotion: { to: { behindBaseline: -6.7, pitch: -0.8, fov: 78 }, duration: 1.2 },
  }),
  ground('volley-left', 'First volley left', 'VOLLEY LEFT', -2.75, -5.2, 74, 'slice', 'Near left', 'Short', {
    family: 'volley', source: { x: -1.2, y: 1.3, z: 3.7 },
    cameraMotion: { to: { behindBaseline: -4.7, fov: 76 }, duration: 1.5 },
  }),
  ground('volley-right', 'Second volley right', 'VOLLEY RIGHT', 2.65, -4.9, 78, 'slice', 'Near right', 'Short', {
    family: 'volley', source: { x: 1.2, y: 1.3, z: 3.2 },
    cameraMotion: { to: { behindBaseline: -7.5, fov: 80 }, duration: 1.25 },
  }),
  ground('lob-deep', 'Defensive lob', 'RETREAT', 0.75, -10.25, 54, 'kick', 'Body', 'Deep', {
    family: 'lob', source: { x: -1.5, y: 1.0, z: 4.1 },
    cameraMotion: { to: { behindBaseline: -1.2, pitch: 3, fov: 78 }, duration: 1.65 },
  }),
  ground('overhead-feed', 'Overhead feed', 'OVERHEAD', -0.75, -9.6, 62, 'kick', 'Near left', 'Deep', {
    family: 'overhead', source: { x: 1.1, y: 2.4, z: 3.4 },
    cameraMotion: { to: { behindBaseline: -1, pitch: 4, fov: 80 }, duration: 1.45 },
  }),
];

export const SHOT_BY_ID = new Map(SHOTS.map((shot) => [shot.id, shot]));

export const DRILLS: readonly DrillDefinitionV1[] = [
  {
    schemaVersion: 1,
    id: 'quick-rally',
    title: 'Crosscourt Rhythm',
    description: 'Alternating deep and medium groundstrokes for timing and recovery.',
    category: 'Quick Rally',
    shotIds: ['fh-cross-deep', 'bh-cross-deep', 'fh-cross-mid', 'bh-cross-high'],
    defaultInterval: 3.2,
    defaultRepetitions: 12,
  },
  {
    schemaVersion: 1,
    id: 'return-practice',
    title: 'Serve Recognition',
    description: 'Read T, body, and wide serves from both service sides.',
    category: 'Return Practice',
    shotIds: ['serve-deuce-t', 'serve-deuce-wide', 'serve-deuce-body', 'serve-ad-t', 'serve-ad-wide', 'serve-ad-body'],
    defaultInterval: 4.5,
    defaultRepetitions: 12,
  },
  {
    schemaVersion: 1,
    id: 'tactical-pattern',
    title: 'Two crosscourt, then line',
    description: 'Two forehands crosscourt, a forehand line change, backhand response, and finish.',
    category: 'Tactical Pattern',
    shotIds: ['fh-cross-deep', 'fh-cross-mid', 'fh-line-deep', 'bh-cross-deep', 'bh-line-deep'],
    defaultInterval: 3.1,
    defaultRepetitions: 10,
  },
  {
    schemaVersion: 1,
    id: 'serve-volley',
    title: 'Serve and close',
    description: 'Return cue, first volley, second volley, then recover.',
    category: 'Serve & Volley',
    shotIds: ['serve-deuce-wide', 'volley-left', 'volley-right', 'lob-deep'],
    defaultInterval: 3.5,
    defaultRepetitions: 8,
  },
  {
    schemaVersion: 1,
    id: 'net-overhead',
    title: 'Two volleys and overhead',
    description: 'Close twice, read the lob, then reposition for the overhead.',
    category: 'Net & Overhead',
    shotIds: ['volley-left', 'volley-right', 'lob-deep', 'overhead-feed'],
    defaultInterval: 3.4,
    defaultRepetitions: 8,
  },
  {
    schemaVersion: 1,
    id: 'baseline-depth-ladder',
    title: 'Depth ladder',
    description: 'Read short, medium, and deep balls without losing recovery rhythm.',
    category: 'Quick Rally',
    shotIds: ['short-angle-left', 'fh-cross-mid', 'bh-cross-deep', 'defensive-high-left'],
    defaultInterval: 3.4,
    defaultRepetitions: 12,
  },
  {
    schemaVersion: 1,
    id: 'baseline-corner-switch',
    title: 'Corner switch',
    description: 'Alternate both deep corners, then recognize the neutral body ball.',
    category: 'Quick Rally',
    shotIds: ['fh-cross-deep', 'bh-cross-deep', 'body-neutral'],
    defaultInterval: 3,
    defaultRepetitions: 12,
  },
  {
    schemaVersion: 1,
    id: 'baseline-short-deep',
    title: 'Short-deep recognition',
    description: 'Move in for a short angle and recover for a high deep response.',
    category: 'Quick Rally',
    shotIds: ['short-angle-right', 'defensive-high-left', 'short-angle-left', 'bh-cross-high'],
    defaultInterval: 3.6,
    defaultRepetitions: 12,
  },
  {
    schemaVersion: 1,
    id: 'return-rhythm-read',
    title: 'Normal and compact rhythm',
    description: 'Separate serve preparation rhythm from pace while reading T and wide locations.',
    category: 'Return Practice',
    shotIds: ['serve-deuce-t', 'serve-deuce-wide', 'serve-ad-t', 'serve-ad-wide'],
    defaultInterval: 4.6,
    defaultRepetitions: 12,
  },
  {
    schemaVersion: 1,
    id: 'return-lefty-patterns',
    title: 'Left-handed serve patterns',
    description: 'Recognize reversed slice and kick directions from both service sides.',
    category: 'Return Practice',
    shotIds: ['serve-left-deuce-wide', 'serve-left-ad-wide', 'serve-deuce-body', 'serve-ad-body'],
    defaultInterval: 4.7,
    defaultRepetitions: 12,
  },
  {
    schemaVersion: 1,
    id: 'return-second-serve',
    title: 'Second-serve pressure',
    description: 'Repeat kick and slice shapes with a forward return-preparation cue.',
    category: 'Return Practice',
    shotIds: ['serve-ad-wide', 'serve-deuce-wide', 'serve-left-ad-wide'],
    defaultInterval: 4.2,
    defaultRepetitions: 12,
  },
  {
    schemaVersion: 1,
    id: 'tactical-inside-out',
    title: 'Inside-out escape',
    description: 'Neutral body ball, inside-out forehand, then change direction down the line.',
    category: 'Tactical Pattern',
    shotIds: ['body-neutral', 'fh-inside-out', 'fh-line-deep', 'bh-cross-deep'],
    defaultInterval: 3.2,
    defaultRepetitions: 8,
  },
  {
    schemaVersion: 1,
    id: 'tactical-approach-close',
    title: 'Approach and close',
    description: 'Recognize the approach ball, move through first and second volley, then recover.',
    category: 'Tactical Pattern',
    shotIds: ['approach-feed', 'volley-left', 'volley-right', 'lob-deep'],
    defaultInterval: 3.5,
    defaultRepetitions: 8,
  },
  {
    schemaVersion: 1,
    id: 'tactical-defend-finish',
    title: 'Defend then finish',
    description: 'Absorb a high defensive ball, reset through the body, and finish down the line.',
    category: 'Tactical Pattern',
    shotIds: ['defensive-high-left', 'body-neutral', 'bh-cross-high', 'fh-line-deep'],
    defaultInterval: 3.7,
    defaultRepetitions: 8,
  },
  {
    schemaVersion: 1,
    id: 'net-half-volley',
    title: 'Half-volley and close',
    description: 'Handle a low body feed, close, then split for the second volley.',
    category: 'Net & Overhead',
    shotIds: ['half-volley-body', 'volley-left', 'volley-right'],
    defaultInterval: 3.2,
    defaultRepetitions: 9,
  },
  {
    schemaVersion: 1,
    id: 'custom-starter',
    title: 'Custom starter',
    description: 'Editable mixed sequence used as a safe local authoring base.',
    category: 'Custom',
    shotIds: ['body-neutral', 'fh-cross-deep', 'bh-cross-deep'],
    defaultInterval: 3.2,
    defaultRepetitions: 9,
  },
];

export const DRILL_BY_CATEGORY = new Map(
  [...new Set(DRILLS.map((drill) => drill.category))].map((category) => [category, DRILLS.find((drill) => drill.category === category)!]),
);
